services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: schedule
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - selenium_net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U maxim -d schedule" ]
      interval: 10s
      timeout: 5s
      retries: 5

  firefox:
    image: selenium/standalone-firefox:137.0.1
    container_name: firefox
    shm_size: 2gb
    ports:
      - "4444:4444"
    networks:
      - selenium_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  schedule-sync:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: schedule-sync

    depends_on:
      postgres:
        condition: service_healthy
      firefox:
        condition: service_healthy

    env_file:
      - .env

    working_dir: /vvsu-schedule
    environment:
      - PYTHONPATH=/vvsu-schedule/src
      - TZ=Asia/Vladivostok

    volumes:
      - ./src:/vvsu-schedule/src
      - ./src/db:/vvsu-schedule/src/db
      - ./logs:/vvsu-schedule/logs
      - .:/vvsu-schedule
      - ./.env:/vvsu-schedule/.env
      - ./src/schedule_vvsu/json/credentials:/vvsu-schedule/src/schedule_vvsu/json/credentials

    networks:
      - selenium_net

    command: >
      /bin/bash -c "
        poetry run alembic upgrade head &&
        poetry run python -m schedule_vvsu.scheduler
      "


  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: schedule-api
    depends_on:
      postgres:
        condition: service_healthy
      firefox:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - PYTHONPATH=/vvsu-schedule/src
      - TZ=Asia/Vladivostok
    volumes:
      - ./src:/vvsu-schedule/src
      - ./logs:/vvsu-schedule/logs
      - ./.env:/vvsu-schedule/.env
      - .:/vvsu-schedule
      - ./src/schedule_vvsu/json/credentials:/vvsu-schedule/src/schedule_vvsu/json/credentials
    working_dir: /vvsu-schedule/src
    networks:
      - selenium_net
    command: ["poetry", "run", "uvicorn", "schedule_vvsu.api:app", "--host", "0.0.0.0", "--port", "8000"]

  bot:
    build:
      context: ./src/tg_bot
      dockerfile: Dockerfile
    command: poetry run python -m app.bot
    working_dir: /app
    volumes:
      - ./src/tg_bot:/app
    env_file:
      - .env
    depends_on:
      - api
      - postgres
    networks:
      - selenium_net


  caddy:
    image: caddy:2
    container_name: caddy
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - api
    networks:
      - selenium_net

volumes:
  pgdata:
  caddy_data:
  caddy_config:

networks:
  selenium_net:
    driver: bridge
