version: "3.8"

services:
  firefox:
    image: selenium/standalone-firefox:137.0.1
    container_name: firefox
    shm_size: 2gb
    ports:
      - "4444:4444"  # WebDriver API
    networks:
      - selenium_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    environment:
      - SE_NODE_SESSION_TIMEOUT=60
      - SE_NODE_MAX_SESSIONS=1
      - SE_JAVA_OPTS=-Dwebdriver.log.file=/tmp/selenium.log

  schedule-sync:
    build: .
    container_name: schedule-sync
    depends_on:
      firefox:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./logs:/app/src/schedule_vvsu/logs
      - ./src/schedule_vvsu/json:/app/src/schedule_vvsu/json
    networks:
      - selenium_net
    command: ["vvsu-cli", "start-scheduler"]

  api:
    build: .
    container_name: schedule-api
    depends_on:
      firefox:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./logs:/app/src/schedule_vvsu/logs
      - ./src/schedule_vvsu/json:/app/src/schedule_vvsu/json
    ports:
      - "8000:8000"
    networks:
      - selenium_net
    command: ["poetry", "run", "uvicorn", "schedule_vvsu.api:app", "--host", "0.0.0.0", "--port", "8000"]

networks:
  selenium_net:
    driver: bridge