version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    container_name: vvsu-postgres
    env_file: [.env]
    environment:
      POSTGRES_DB: schedule
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d schedule"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [selenium_net]

  selenium:
    image: selenium/standalone-firefox:137.0.1
    container_name: vvsu-selenium
    shm_size: 2g
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "4444:4444"
    networks: [selenium_net]

  # FastAPI + hot reload
  schedule-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: schedule-api
    working_dir: /vvsu-schedule/src
    command: >
      poetry run uvicorn schedule_vvsu.api:app
      --host 0.0.0.0 --port 8000
      --reload --reload-dir /vvsu-schedule/src
    env_file: [.env]
    environment:
      - PYTHONPATH=/vvsu-schedule/src
      - TZ=Asia/Vladivostok
    depends_on:
      selenium:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - ./src:/vvsu-schedule/src
      - ./logs:/vvsu-schedule/logs
      - ./.env:/vvsu-schedule/.env
      - ./src/schedule_vvsu/json/credentials:/vvsu-schedule/src/schedule_vvsu/json/credentials
      - .:/vvsu-schedule
    networks: [selenium_net]
    expose: ["8000"]

  schedule-sync:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: schedule-sync
    working_dir: /vvsu-schedule
    command: >
      /bin/bash -lc
      "poetry run alembic upgrade head &&
       poetry run watchfiles --ignore-path logs 'python -m schedule_vvsu.scheduler'"
    env_file: [.env]
    environment:
      - PYTHONPATH=/vvsu-schedule/src
      - TZ=Asia/Vladivostok
    depends_on:
      selenium:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - ./src:/vvsu-schedule/src
      - ./logs:/vvsu-schedule/logs
      - ./.env:/vvsu-schedule/.env
      - ./src/schedule_vvsu/json/credentials:/vvsu-schedule/src/schedule_vvsu/json/credentials
      - .:/vvsu-schedule
    networks: [selenium_net]

  schedule-bot:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: schedule-bot
    working_dir: /vvsu-schedule/src
    command: poetry run python -m schedule_vvsu.bot
    env_file: [.env]
    environment:
      - PYTHONPATH=/vvsu-schedule/src
      - TZ=Asia/Vladivostok
    depends_on:
      selenium:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - ./src:/vvsu-schedule/src
      - ./logs:/vvsu-schedule/logs
      - ./.env:/vvsu-schedule/.env
      - ./src/schedule_vvsu/json/credentials:/vvsu-schedule/src/schedule_vvsu/json/credentials
      - .:/vvsu-schedule
    networks: [selenium_net]

  caddy:
    image: caddy:2
    container_name: vvsu-caddy
    depends_on: [schedule-api]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks: [selenium_net]

volumes:
  pgdata:
  caddy_data:
  caddy_config:

networks:
  selenium_net:
    driver: bridge
