services:
  chrome-standalone:
    image: selenium/standalone-chrome
    container_name: chrome-standalone
    platform: linux/amd64
    ports:
      - "4444:4444"

  schedule-sync:
    build: .
    container_name: schedule-sync
    depends_on:
      - chrome-standalone
    environment:
      SELENIUM_REMOTE_URL: "http://chrome-standalone:4444/wd/hub"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
